### ISSUE TITLE
configure GitHub Action so CI/CD only runs on push to master

### ISSUE THREAD

**Issue by rory-hurley-gds** [alphagov/govuk-content-metadata#51]
At the moment, GitHub Action runs on every pr.
This is not ideal.

What would be better is if it is triggered only when merged into main. Change to the following...
```
on:
  push:
    branches:
      - master
```
