### ISSUE TITLE
DRAFT - spacy project pull is not downloading all files

### ISSUE THREAD

**Issue by exfalsoquodlibet** [alphagov/govuk-content-metadata#72]
Hi,

Our team is encountering problems when using `spacy project pull` to fetch outputs from the default remote (a bucket on Google Storage):
- the command does not fetch all the outputs (it usually fails to download `training/model-best` and `metrics/metrics.json` as for the below project.yml file);
- the command does not fetch any outputs at all when created by another team member working on the same project;
- the folder assets structure is however recreated, albeit with folder partially or fully empty. 

Checking the outputs hashes on the remote, these are updated as expected when the pipeline is re-run and seem to reflect the changes that have occurred.

We are not sure whether this is a problem with our `project.yml` file and perhaps some misunderstanding on the underlying working of `spacy project push/pull` which we hope someone could clarify.

**Environment specification**

The spacy project pipeline is run within a Docker container deployed on a Google Vertex AI VM with GPU:
- Base image : nvidia/cuda:11.2.1-runtime-ubuntu20.04
- Python version: 3.8
- spacy[cuda112]

 **project.yml** 

The data assets is available locally and pushed with the container when the docker image is built.

```
vars:
  config: "config.cfg"
  gpu_id: 0
  files:
    train_file: "data.jsonl"
  prodigy:
    prodigy-dataset: "dataset-from-data"
  gcp_storage_remote: "gs://$PROJECT/$BUCKET"

remotes:
  default: '${vars.gcp_storage_remote}'

directories: ["assets", "training", "configs", "metrics", "corpus"]

assets:
  - dest: "assets/${vars.files.train_file}"
    description: "JSONL-formatted training data exported from Prodigy"

workflows:
  all:
    - get-assets
    - db-in
    - create-config
    - data-to-spacy
    - train_spacy
    - evaluate
    - push_remote

commands:

  - name: get-assets
    script:
      - "python3 -m spacy project assets"
    help: "Fetch project assets"

  - name: db-in
    help: "Load the annotated .jsonl file in as a prodigy database."
    script:
      - "python3 -m prodigy db-in ${vars.prodigy.prodigy-dataset} assets/${vars.files.train_file}"
    deps:
      - "assets/${vars.files.train_file}"

  - name: create-config
    help: "Initialise and save a config.cfg file using the recommended settings for your use case"
    script:
      - "python3 -m spacy init config configs/${vars.config} --lang en --pipeline transformer,ner --optimize accuracy --gpu --force"
    outputs:
      - "configs/${vars.config}"

  - name: data-to-spacy
    help: "Convert annotated data to spaCy's binary format and create a train and a dev set based on the provided split threshold"
    script:
      - "python3 -m prodigy data-to-spacy ./corpus --ner ${vars.prodigy.prodigy-dataset} --eval-split 0.2 --verbose --config configs/${vars.config}"
    outputs:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"

  - name: train_spacy
    help: "Train a named entity recognition model with spaCy"
    script:
      - "python3 -m spacy train configs/${vars.config} --output training/ --paths.train corpus/train.spacy --paths.dev corpus/dev.spacy --gpu-id ${vars.gpu_id}"
    deps:
      - "corpus/train.spacy"
      - "corpus/dev.spacy"
    outputs:
      - "training/model-best"

  - name: "evaluate"
    help: "Evaluate the model and export metrics"
    script:
      - "python -m spacy evaluate training/model-best corpus/dev.spacy --output metrics/metrics.json"
    deps:
      - "corpus/dev.spacy"
      - "training/model-best"
    outputs:
      - "metrics/metrics.json"

  - name: push_remote
    help: "Push outputs to remote"
    script:
      - "python3 -m spacy project push default"
    deps:
      - "training/model-best"
      - "metrics/metrics.json"

  # clean up files (not in workflow by default)
  - name: clean
    help: "Remove intermediate files"
    script:
      - "rm -rf training/*"
      - "rm -rf metrics/*"
      - "rm -rf corpus/*"
```
